data:
  dataset_config: ../dataset_dependent_configs/cam16/cam_univ1_dt_config.yaml
  artifact_dir: ../dataset_dependent_configs/cam16/out/clam/cam_uni_lvl2
  data_dims: 1024    # Embeddings dimensions Resnet50:1024, CONCH: 512, UNIv1: 1024, HOPTIMUS: 1536
  use_h5: True
  num_classes: 2
  split: 0

model:
  attention: clam # [gp, clam, transmil, mil]
  variant: sb # [sb, mb] for single or multi branch
  model_size: big
  feature_extractor: univ1_lvl2 # [resnet50, conch, univ1, hoptimus]
  gate: True
  embed_dim: 1024
  dropout: 0.25
  B: 32
  instance_loss_fn: 'svm' # [svm, cross_entropy]
  bag_loss_fn: 'ce' # [svm, cross_entropy]
  bag_weight: 0.7 # weight coefficient for bag level loss i.e. bag_weight * bag_loss + (1-bag_weight) * instance_loss
  subtyping: False
  print_model: True

logging:
  save_predictions: True
  run_name: test_run  # Can be set to auto
  tracking_url: ./mlruns
  high_conf_metrics: False
  wandb: True
  project: CAMELYON16  # Name of the project in wandb i.e. Dataset name
  model_ckpt_dir: ../experiments/clam_sb_time # Path to the directory where the model checkpoints will be saved
  model_version: time


seed: 2021   # Seed for everything with the seed_torch function from main.py
phase: train # train, test

training:
  max_epochs: 50
  gpu_index: [0]
  strategy: auto
  precision: '32'
  patience: 200 # Early stopping patience
  optimizer: adam
  reg: 5.e-3 #  weight decay regularization
  scheduler: lambda # [lamda, cosine, linearcosine]
  learning_rate: 2.e-4  # 0.0001 reasonable choice
  # stuff exclusively for lamda scheduler
  lr_decay_after_epoch: 102    # Tune the decay factors
  stop_decay_after_epoch: 103
  stop_decay_lr_value: 0.00002 # Stop decaying the learning rate after this lr value
  lr_decay_factor: 0.5
  min_delta: 0.0001
  # stuff exclusively for cosine/linearcosine scheduler
  min_lr: 1.e-5
  # stuff exclusively for linearcosine scheduler
  warmup_epochs: 20
  warmup_lr: 1.e-5
  lr_logging_interval: epoch  # Log learning rate ['step', 'epoch', None]
  lr_logging_frequency: 1 # Log learning rate every n steps/epochs
  log_weight_decay: True

testing:
  experiment_ckpt_dir: ../experiments/clam_sb_v0/UNIv1_CAM16_lvl2_224_features/0/last.ckpt

