data:
  csv_path: /path/to/labels.csv # Path to labels.csv
  data_root_dir: /path/to/dir/containing/features/ # Path to the root directory of the dataset
  split_dir: /path/to/dir/containing/splits/ # Path to the directory containing the splits
  feature_extractor: UNIv1 # current feature extractor (ResNet50, UNIv1, HOPTIMUS, CONCH)
  print_info: True
  label_dict: {'normal':0, 'tumor':1} # Dictionary to map labels to integers
  patient_strat: False
  num_classes: 2
  type: binary
  shape_file: ../images_shapes_lvl0/cam16_images_shape.txt

logging:
  feature_extractor: UNIv1_lvl2 # current feature extractor
  group: agp_univ1 # In the form of model type_feature extractor
  model_chkpt_dir: ./experiments # Path to the directory where the model checkpoints will be saved


