data:
  csv_path: ~/Code/custom_framework/dataset_dependent_configs/tcga-nsclc/filtered_labels.csv # Path to labels.csv
  data_root_dir: /mnt/features/TCGA_datasets/NSCLC/NSCLC_CONCHv1_10x_coords/CONCHv1_NSCLC_10x_features # Path to dir containing h5 and pt files
  split_dir: ~/Code/custom_framework/dataset_dependent_configs/tcga-nsclc/splits/ # Path to the directory containing the splits
  feature_extractor: CONCHv1 # current feature extractor (ResNet50, UNIv1, HOPTIMUS, CONCH)
  print_info: True
  label_dict: {'LUSC':0, 'LUAD':1} # Dictionary to map labels to integers
  patient_strat: True
  num_classes: 2
  type: binary
  shape_file: ../images_shapes_lvl0/nsclc_images_shape.txt

logging:
  feature_extractor: CONCHv1_lvl2 # current feature extractor
  group: agp_conchv1 # In the form of model type_feature extractor
  model_chkpt_dir: ../experiments # Path to the directory where the model checkpoints will be saved


