data:
  dataset_config: ../dataset_dependent_configs/cam16/cam_univ1_dt_config.yaml
  artifact_dir: ../dataset_dependent_configs/cam16/out/dgrmil/cam_univ1_lvl2
  data_dims: 1024 # Embeddings dimensions Resnet50:1024, CONCH: 512, UNIv1: 1024, HOPTIMUS: 1536
  num_classes: 2
  use_h5: True
  split: 0 # Split number, must be int

model:
  attention: dgrmil # [clam, transmil, mil, dgrmil]
  variant: null # [sb, mb] for single or multi branch
  model_size: null
  feature_extractor: univ1_lvl2 # [resnet50, conch, univ1, hoptimus]
  attn_mode: 'gated'
  embed_dim: 1024
  L: 512
  num_les: 5 # Number of representation for normal/lesion
  dropout: 0.4 # bag classifier dropout rate
  dropout_patch: 0.1 # patch dropout rate
  B: null
  instance_loss_fn: null
  bag_loss_fn: 'ce' # [ce, svm, bcewlogits] for abmil, transmil, clam, does not work for dgrmil
  bag_weight: null
  subtyping: null
  print_model: True

logging:
  save_predictions: True
  run_name: test_run  # Can be set to auto
  tracking_url: ./mlruns
  high_conf_metrics: False
  wandb: True
  project: CAMELYON16  # Name of the project in wandb i.e. Dataset name
  model_ckpt_dir: ../experiments/dgrmil # Path to the directory where the model checkpoints will be saved
  model_version: time

seed: 2024   # Seed for everything with the seed_torch function from main.py
phase: train # train, test

training:
  max_epochs: 15
  gpu_index: [0]
  strategy: auto
  precision: '32' # 32 or 64 (64 if gpu has enough memory)
  patience: 200 # Early stopping patience
  optimizer: adam # [adam, sgd, lookahead_radam]
  reg: 1.e-4 # weight decay
  opt_eps: 1.e-8 # Adam epsilon not implemented currently
  opt_betas: [0.9, 0.999] # Adam betas, not implemented currently
  momentum: 0.9 # sgd momentum, doesn't do anything for other optimizers
  scheduler: lambda # [lamda, cosine, linearcosine]
  learning_rate: 1.e-4  # 0.0001 reasonable choice
  # stuff exclusively for lamda scheduler
  lr_decay_after_epoch: 200    # Tune the decay factors
  stop_decay_after_epoch: 201
  stop_decay_lr_value: 2.e-5 # Stop decaying the learning rate after this lr value
  lr_decay_factor: 5.e-1
  min_delta: 1.e-4
  # stuff exclusively for cosine/linearcosine scheduler
  min_lr: 1.e-5  # eta_min
  # stuff exclusively for linearcosine scheduler
  warmup_epochs: 5 # 20
  warmup_lr: 1.e-5 # warmup start learning_rate
  lr_logging_interval: epoch  # Log learning rate ['step', 'epoch', None]
  lr_logging_frequency: 1 # Log learning rate every n steps/epochs
  log_weight_decay: True

testing:
  experiment_ckpt_dir: ../experiments/dgrmil_v0/UNIv1_CAM16_lvl2_224_features/6/last.ckpt

