data:
  dataset_config: ../dataset_dependent_configs/tcga-nsclc/nsclc_univ1_dt_config.yaml
  artifact_dir: ../dataset_dependent_configs/tcga-nsclc/out/transmil/nsclc_uni_lvl2
  data_dims: 1024 # Embeddings dimensions Resnet50:1024, CONCH: 512, UNIv1: 1024, HOPTIMUS: 1536
  num_classes: 2
  use_h5: True
  split: 0 # Split number, must be int

model:
  attention: transmil # [clam, transmil, mil]
  variant: null # [sb, mb] for single or multi branch
  model_size: null
  feature_extractor: univ1_lvl2 # [resnet50, conch, univ1, hoptimus]
  gate: null
  embed_dim: 1024
  dropout: null
  B: null
  instance_loss_fn: null
  bag_loss_fn: 'ce' # [ce, svm]
  bag_weight: null
  subtyping: null
  print_model: False

logging:
  save_predictions: True
  run_name: test_run  # Can be set to auto
  tracking_url: ./mlruns
  high_conf_metrics: False
  wandb: True
  project: NSCLC  # Name of the project in wandb i.e. Dataset name
  model_ckpt_dir: ../experiments/transmil # Path to the directory where the model checkpoints will be saved
  model_version: v0

seed: 2024   # Seed for everything with the seed_torch function from main.py
phase: train # train, test

training:
  max_epochs: 12
  gpu_index: [4]
  strategy: auto
  precision: '32' # 32 or 64 (64 if gpu has enough memory)
  patience: 200 # Early stopping patience
  optimizer: lookahead_radam # [adam, sgd, lookahead_radam]
  reg: 1.e-5 # weight decay
  opt_eps: 1.e-8 # Adam epsilon not implemented currently
  opt_betas: [0.9, 0.999] # Adam betas, not implemented currently
  momentum: null 
  scheduler: linearcosine # [lamda, cosine, linearcosine]
  learning_rate: 4.e-4  # 0.0001 reasonable choice
  # stuff exclusively for lamda scheduler
  lr_decay_after_epoch: 40    # Tune the decay factors
  stop_decay_after_epoch: 41
  stop_decay_lr_value: 2.e-5 # Stop decaying the learning rate after this lr value
  lr_decay_factor: 5.e-1
  min_delta: 1.e-4
  # stuff exclusively for cosine/linearcosine scheduler
  min_lr: 1.e-5
  # stuff exclusively for linearcosine scheduler
  warmup_epochs: 3
  warmup_lr: 1.e-5
  lr_logging_interval: epoch  # Log learning rate ['step', 'epoch', None]
  lr_logging_frequency: 1 # Log learning rate every n steps/epochs
  log_weight_decay: True

testing:
  experiment_ckpt_dir: ../experiments/transmil_v0/UNIv1_NSCLC_10x_features/0/last.ckpt

